KAREL_DIR= ../src
OUT_DIR = ..

all:
	g++ -D_LINUX -I../../Hoe3D/src -I../../HoeGame -L/usr/X11R6/lib -L../../HoeGame -o $(OUT_DIR)/Karel3D $(KAREL_DIR)/karel3d_app.cpp $(KAREL_DIR)/main.cpp  -ldl -lX11 -lHoeGame
 
